// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BoardHunt.Pay {
	
	
	public partial class OrderForm {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm Form1;
		
		protected System.Web.UI.WebControls.Label lblPageTitle;
		
		protected System.Web.UI.WebControls.Label lblPageTitleMsg;
		
		protected System.Web.UI.WebControls.Panel pnlError;
		
		protected System.Web.UI.WebControls.Label lblErrorMessage;
		
		protected System.Web.UI.WebControls.Label lblItemTitle;
		
		protected System.Web.UI.WebControls.DropDownList cboItemList;
		
		protected System.Web.UI.WebControls.Image imgItem;
		
		protected System.Web.UI.WebControls.Label lblItemDesc;
		
		protected System.Web.UI.WebControls.DropDownList cboRefer;
		
		protected System.Web.UI.WebControls.Label lblQuantity;
		
		protected System.Web.UI.WebControls.TextBox txtQuantity;
		
		protected System.Web.UI.WebControls.Button btnUpdate;
		
		protected System.Web.UI.WebControls.Label lblShipping;
		
		protected System.Web.UI.WebControls.Label lblUnitPrice;
		
		protected System.Web.UI.WebControls.Label lblLegalStuff;
		
		protected System.Web.UI.WebControls.Label lblSubTotal;
		
		protected System.Web.UI.WebControls.Label lblShippingAmt;
		
		protected System.Web.UI.WebControls.Label lblPromo;
		
		protected System.Web.UI.WebControls.TextBox txtPromo;
		
		protected System.Web.UI.WebControls.Button btnPCode;
		
		protected System.Web.UI.WebControls.LinkButton lnkBack;
		
		protected System.Web.UI.WebControls.Label lblTotal;
		
		protected System.Web.UI.WebControls.LinkButton lnkCancel;
		
		protected System.Web.UI.WebControls.Button btnCancel;
		
		protected System.Web.UI.WebControls.ImageButton imgBtnPay;
		
		protected System.Web.UI.WebControls.Label lblClosing;
		
		protected System.Web.UI.WebControls.Label lblPrice;
		
		protected System.Web.UI.WebControls.RadioButtonList txtCCType;
		
		protected System.Web.UI.WebControls.TextBox txtOrderAmount;
		
		protected System.Web.UI.WebControls.Button btnSubmit;
		
		protected System.Web.UI.WebControls.Button btnSubscribe;
		
		protected System.Web.UI.WebControls.HiddenField hdnDiscountAmt;
		
		protected System.Web.UI.WebControls.HiddenField hdnInvoiceNo;
		
		protected System.Web.UI.WebControls.HiddenField hdnTxnId;
		
		protected System.Web.UI.WebControls.HiddenField hdnServiceName;
		
		protected System.Web.UI.WebControls.HiddenField hdnServiceVal;
		
		protected System.Web.UI.WebControls.HiddenField hdnUnitPrice;
		
		protected System.Web.UI.WebControls.HiddenField hdnShippingPrice;
		
		protected System.Web.UI.WebControls.HiddenField hdnUserDir;
		
		protected System.Web.UI.WebControls.HiddenField hdnDlftQ;
		
		protected System.Web.UI.WebControls.HiddenField hdnGenData;
	}
}
