//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardHunt.Qna {
    
    
    public partial class List {
        
        /// <summary>
        /// Form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;
        
        /// <summary>
        /// pnlFilter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlFilter;

        protected global::System.Web.UI.WebControls.TextBox txtFilterKwd;

        protected global::System.Web.UI.WebControls.Button btnSearch;

        protected global::System.Web.UI.WebControls.Label lblLocation;

        protected global::System.Web.UI.WebControls.Label lblCount;

        protected global::System.Web.UI.WebControls.Label lblNoResult;

        protected global::System.Web.UI.WebControls.DataList dlEntryList;

        protected global::System.Web.UI.WebControls.ImageButton cmdPrev;
        
       
        protected global::System.Web.UI.WebControls.Label lblCurrentPage;

        protected global::System.Web.UI.WebControls.PlaceHolder placeHolder;

        protected global::System.Web.UI.WebControls.ImageButton cmdNext;

        protected global::System.Web.UI.WebControls.HiddenField hdnBackColor;

        protected global::System.Web.UI.WebControls.HiddenField hdnLocVal;

        protected global::BoardHunt.include.Controls.Boost boost1;

        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
