// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BoardHunt {
	
	
	public partial class contact {
		
		protected System.Web.UI.HtmlControls.HtmlForm Form1;
		
		protected System.Web.UI.WebControls.Panel panelSendEmail;
		
		protected System.Web.UI.WebControls.TextBox name;
		
		protected System.Web.UI.WebControls.TextBox email;
		
		protected System.Web.UI.WebControls.DropDownList cboSubject;
		
		protected System.Web.UI.WebControls.TextBox message;
		
		protected System.Web.UI.WebControls.Button btnSend;
		
		protected System.Web.UI.WebControls.CustomValidator CustomValidator1;
		
		protected System.Web.UI.WebControls.Label lblErrorMsg;
		
		protected System.Web.UI.WebControls.Panel panelMailSent;
	}
}
