// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BoardHunt {
	
	
	public partial class edit_item {
		
		protected System.Web.UI.HtmlControls.HtmlForm Form1;
		
		protected System.Web.UI.WebControls.HyperLink lnkMenu;
		
		protected System.Web.UI.WebControls.HyperLink lnkManage;
		
		protected System.Web.UI.WebControls.Label lblPageTitle;
		
		protected System.Web.UI.WebControls.Panel pnlAll;
		
		protected System.Web.UI.WebControls.Panel pnlSold;
		
		protected System.Web.UI.WebControls.Button btnBoost;
		
		protected System.Web.UI.WebControls.Button btnSold;
		
		protected System.Web.UI.WebControls.Panel pnlLocation;
		
		protected System.Web.UI.WebControls.DropDownList cboRegion;
		
		protected System.Web.UI.WebControls.TextBox txtTown;
		
		protected System.Web.UI.WebControls.Panel pnlBoardType;
		
		protected System.Web.UI.WebControls.DropDownList cboBoardType;
		
		protected System.Web.UI.WebControls.CheckBox chkOther;
		
		protected System.Web.UI.WebControls.TextBox txtOtherBoard;
		
		protected System.Web.UI.WebControls.Panel pnlGearItem;
		
		protected System.Web.UI.WebControls.TextBox txtGearItem;
		
		protected System.Web.UI.WebControls.Panel pnlBrand;
		
		protected System.Web.UI.WebControls.TextBox txtBrand;
		
		protected System.Web.UI.WebControls.CustomValidator CustomValidator2;
		
		protected System.Web.UI.WebControls.TextBox txtShaper;
		
		protected System.Web.UI.WebControls.Panel pnlModel;
		
		protected System.Web.UI.WebControls.TextBox txtModel;
		
		protected System.Web.UI.WebControls.Panel pnlHeight;
		
		protected System.Web.UI.WebControls.TextBox txtHtFt;
		
		protected System.Web.UI.WebControls.Label lblFtHt;
		
		protected System.Web.UI.WebControls.TextBox txtHtIn;
		
		protected System.Web.UI.WebControls.Label lblFtIn;
		
		protected System.Web.UI.WebControls.CustomValidator CustomValidator3;
		
		protected System.Web.UI.WebControls.Panel pnlSurfOnly;
		
		protected System.Web.UI.WebControls.TextBox txtWidth;
		
		protected System.Web.UI.WebControls.TextBox txtWidthNum;
		
		protected System.Web.UI.WebControls.TextBox txtWidthDNum;
		
		protected System.Web.UI.WebControls.CustomValidator CustomValidator4;
		
		protected System.Web.UI.WebControls.TextBox txtThick;
		
		protected System.Web.UI.WebControls.TextBox txtThickNum;
		
		protected System.Web.UI.WebControls.TextBox txtThickDNum;
		
		protected System.Web.UI.WebControls.CustomValidator CustomValidator9;
		
		protected System.Web.UI.WebControls.DropDownList cboFins;
		
		protected System.Web.UI.WebControls.DropDownList cboTailType;
		
		protected System.Web.UI.WebControls.Panel pnlGenDims;
		
		protected System.Web.UI.WebControls.Label lblGenDims;
		
		protected System.Web.UI.WebControls.TextBox txtGenDims;
		
		protected System.Web.UI.WebControls.TextBox txtPrice;
		
		protected System.Web.UI.WebControls.CustomValidator CustomValidator5;
		
		protected System.Web.UI.WebControls.Label lblShipping;
		
		protected System.Web.UI.WebControls.RadioButtonList rdoShip;
		
		protected System.Web.UI.WebControls.TextBox txtDetails;
		
		protected System.Web.UI.WebControls.Panel pnlVideo;
		
		protected System.Web.UI.WebControls.TextBox txtVideo;
		
		protected System.Web.UI.WebControls.Button btnShowPnl;
		
		protected System.Web.UI.WebControls.Panel pnlAddImages;
		
		protected System.Web.UI.WebControls.Image img1;
		
		protected System.Web.UI.WebControls.RadioButtonList rdoImgMgr1;
		
		protected System.Web.UI.WebControls.Image img2;
		
		protected System.Web.UI.WebControls.RadioButtonList rdoImgMgr2;
		
		protected System.Web.UI.HtmlControls.HtmlInputFile File1;
		
		protected System.Web.UI.WebControls.CustomValidator CustomValidator1;
		
		protected System.Web.UI.HtmlControls.HtmlInputFile File2;
		
		protected System.Web.UI.WebControls.CustomValidator CustomValidator6;
		
		protected System.Web.UI.WebControls.Image img3;
		
		protected System.Web.UI.WebControls.RadioButtonList rdoImgMgr3;
		
		protected System.Web.UI.WebControls.Image img4;
		
		protected System.Web.UI.WebControls.RadioButtonList rdoImgMgr4;
		
		protected System.Web.UI.HtmlControls.HtmlInputFile File3;
		
		protected System.Web.UI.WebControls.CustomValidator CustomValidator7;
		
		protected System.Web.UI.HtmlControls.HtmlInputFile File4;
		
		protected System.Web.UI.WebControls.CustomValidator CustomValidator8;
		
		protected System.Web.UI.WebControls.Button btnCancel;
		
		protected System.Web.UI.WebControls.Button btnFinish;
		
		protected System.Web.UI.WebControls.Label lblStatus;
		
		protected System.Web.UI.WebControls.HiddenField HiddenField1;
		
		protected System.Web.UI.WebControls.HiddenField HiddenField2;
		
		protected System.Web.UI.WebControls.HiddenField HiddenField3;
		
		protected System.Web.UI.WebControls.HiddenField HiddenField4;
		
		protected System.Web.UI.WebControls.Label lbl2;
		
		protected System.Web.UI.WebControls.HiddenField hdnActCode;
		
		protected System.Web.UI.WebControls.HiddenField hdnEntryId;
		
		protected System.Web.UI.WebControls.HiddenField hdnPrice;
		
		protected System.Web.UI.WebControls.HiddenField hdnEntryType;
	}
}
