//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardHunt {
    
    
    public partial class post_manager {

        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;

        protected global::System.Web.UI.WebControls.HyperLink lnkMenu;
 
        protected global::System.Web.UI.WebControls.Label lblCount;
        

        protected global::System.Web.UI.WebControls.Label lblNoResult;

        protected global::System.Web.UI.WebControls.DataList dlEntryList;
        

        protected global::System.Web.UI.WebControls.ImageButton cmdPrev;
  
        protected global::System.Web.UI.WebControls.Label lblCurrentPage;
        
  
        protected global::System.Web.UI.WebControls.ImageButton cmdNext;
 
        protected global::System.Web.UI.WebControls.Button btnCancel;

        protected global::System.Web.UI.WebControls.Button btnUpdate;

        protected global::System.Web.UI.WebControls.HiddenField hdnAdType;
        

        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
