// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BoardHunt {
	
	
	public partial class post_finish {
		
		protected System.Web.UI.HtmlControls.HtmlForm Form1;
		
		protected System.Web.UI.WebControls.Image imgCheckDone;
		
		protected System.Web.UI.WebControls.Panel pnlBoost;
		
		protected System.Web.UI.WebControls.Label lblMessage;
		
		protected System.Web.UI.WebControls.LinkButton btnUpgradePro;
		
		protected System.Web.UI.WebControls.LinkButton lnkFBShare;
		
		protected System.Web.UI.WebControls.ImageButton ImageButton1;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor lnkViewPost;
		
		protected System.Web.UI.WebControls.Label txtEntryLink;
		
		protected System.Web.UI.WebControls.HyperLink hypLnkPost;
		
		protected System.Web.UI.WebControls.HyperLink hypLnkPostModel;
		
		protected System.Web.UI.WebControls.HyperLink lnkPostItem;
		
		protected System.Web.UI.WebControls.HyperLink lnkLivePost;
		
		protected System.Web.UI.WebControls.HiddenField hdnEntryVal;
	}
}
