// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BoardHunt {
	
	
	public partial class preview_post {
		
		protected System.Web.UI.HtmlControls.HtmlForm Form1;
		
		protected System.Web.UI.WebControls.Button btnEditTop;
		
		protected System.Web.UI.WebControls.Button btnFinishTop;
		
		protected System.Web.UI.WebControls.Panel pnlError;
		
		protected System.Web.UI.WebControls.Panel pnlDetails;
		
		protected System.Web.UI.WebControls.Image Pic1;
		
		protected System.Web.UI.WebControls.Image Pic2;
		
		protected System.Web.UI.WebControls.Image Pic3;
		
		protected System.Web.UI.WebControls.Image Pic4;
		
		protected System.Web.UI.WebControls.Image Pic1ThmbNail;
		
		protected System.Web.UI.WebControls.Image Pic2ThmbNail;
		
		protected System.Web.UI.WebControls.Image Pic3ThmbNail;
		
		protected System.Web.UI.WebControls.Image Pic4ThmbNail;
		
		protected System.Web.UI.WebControls.Label lblDateData;
		
		protected System.Web.UI.WebControls.Label lblLocation;
		
		protected System.Web.UI.WebControls.Label lblGearItem;
		
		protected System.Web.UI.WebControls.Label lblGearItemData;
		
		protected System.Web.UI.WebControls.Panel pnlModel;
		
		protected System.Web.UI.WebControls.Label lblModel;
		
		protected System.Web.UI.WebControls.Label lblModelData;
		
		protected System.Web.UI.WebControls.Label lblBrand;
		
		protected System.Web.UI.WebControls.Label lblBrandData;
		
		protected System.Web.UI.WebControls.Label lblBoardType;
		
		protected System.Web.UI.WebControls.Label lblBoardTypeData;
		
		protected System.Web.UI.WebControls.Label lblHeight;
		
		protected System.Web.UI.WebControls.Label lblHeightFtData;
		
		protected System.Web.UI.WebControls.Label lblHeightInData;
		
		protected System.Web.UI.WebControls.Label Label1;
		
		protected System.Web.UI.WebControls.Label lblWidthData;
		
		protected System.Web.UI.WebControls.Label Label11;
		
		protected System.Web.UI.WebControls.Label lblThick;
		
		protected System.Web.UI.WebControls.Label Label2;
		
		protected System.Web.UI.WebControls.Label lblTailData;
		
		protected System.Web.UI.WebControls.Label Label3;
		
		protected System.Web.UI.WebControls.Label lblFinsData;
		
		protected System.Web.UI.WebControls.Panel pnlGenDims;
		
		protected System.Web.UI.WebControls.Label Label6;
		
		protected System.Web.UI.WebControls.Label lblGenDims;
		
		protected System.Web.UI.WebControls.Panel pnlWeb;
		
		protected System.Web.UI.WebControls.Label Label7;
		
		protected System.Web.UI.WebControls.Label lblWeb;
		
		protected System.Web.UI.WebControls.Label Label4;
		
		protected System.Web.UI.WebControls.Label lblDetailsData;
		
		protected System.Web.UI.WebControls.Label lblPrice;
		
		protected System.Web.UI.WebControls.Label lblPriceData;
		
		protected System.Web.UI.WebControls.Label Label5;
		
		protected System.Web.UI.WebControls.Label Label8;
		
		protected System.Web.UI.WebControls.Label Label9;
		
		protected System.Web.UI.WebControls.LinkButton lnkEmailData;
		
		protected System.Web.UI.WebControls.Label Label10;
		
		protected System.Web.UI.WebControls.Label lblPhoneData;
		
		protected System.Web.UI.WebControls.Label lblStatus;
		
		protected System.Web.UI.WebControls.Button btnEdit;
		
		protected System.Web.UI.WebControls.Button btnSave;
		
		protected System.Web.UI.WebControls.Button btnPublish;
		
		protected System.Web.UI.WebControls.HiddenField hdnProcPics;
		
		protected System.Web.UI.WebControls.HiddenField hdnUserDir;
		
		protected System.Web.UI.WebControls.HiddenField hdnAdType;
		
		protected System.Web.UI.WebControls.Panel pnlLocation;
		
		protected System.Web.UI.WebControls.Panel pnlGearItem;
		
		protected System.Web.UI.WebControls.Panel pnlShaper;
		
		protected System.Web.UI.WebControls.Panel pnlBoardType;
		
		protected System.Web.UI.WebControls.Panel pnlAll;
		
		protected System.Web.UI.WebControls.Panel pnlWidth;
		
		protected System.Web.UI.WebControls.Panel pnlSurfOnly;
		
		protected System.Web.UI.WebControls.Panel pnlContact;
	}
}
