// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BoardHunt {
	
	
	public partial class register_user {
		
		protected System.Web.UI.HtmlControls.HtmlForm Form1;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.TextBox txtPassword1;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvPassword;
		
		protected System.Web.UI.WebControls.CustomValidator CustomValidator1;
		
		protected System.Web.UI.WebControls.TextBox txtPhoneNum;
		
		protected System.Web.UI.WebControls.RadioButtonList radioAcctType;
		
		protected System.Web.UI.WebControls.DropDownList cboMerchantType;
		
		protected System.Web.UI.WebControls.CheckBox chkUpgrade;
		
		protected System.Web.UI.WebControls.CheckBox chkUpgrade2;
		
		protected System.Web.UI.WebControls.Panel pnlError;
		
		protected System.Web.UI.WebControls.Label lblStatus;
		
		protected System.Web.UI.WebControls.Button btnFinish;
		
		protected System.Web.UI.WebControls.HiddenField hdnMeVal;
	}
}
