//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardHunt {
    
    
    /// <summary>
    /// SubscriptionManager class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class SubscriptionManager {

        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;

        protected global::System.Web.UI.WebControls.DataList dlEntryList;

        protected global::System.Web.UI.WebControls.Label lblStatus;
    }
}
