//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardHunt {
    
    
	public partial class Surfboardsforsale2 {

        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;

        protected global::System.Web.UI.WebControls.Label lblLocation;
        

        protected global::System.Web.UI.WebControls.HyperLink HypLoc;

        protected global::System.Web.UI.WebControls.Label lblCat;

        protected global::System.Web.UI.WebControls.Label lblNoResult;
        

        protected global::System.Web.UI.WebControls.Label lblCount;

        protected global::BoardHunt.include.Controls.BoostHoriz boost;

        protected global::System.Web.UI.WebControls.Panel pnlFilter;
        

        protected global::System.Web.UI.WebControls.Button btnSearch2;

        protected global::System.Web.UI.WebControls.DropDownList cboLocation;

        protected global::System.Web.UI.WebControls.DropDownList cboBoardType;

        protected global::System.Web.UI.WebControls.TextBox txtFilterKwd;

        protected global::System.Web.UI.WebControls.TextBox txtMinPrice;

        protected global::System.Web.UI.WebControls.TextBox txtMaxPrice;

        protected global::System.Web.UI.WebControls.TextBox txtHtFt;

        protected global::System.Web.UI.WebControls.TextBox txtHtIn;

        protected global::System.Web.UI.WebControls.TextBox txtHtFtMax;

        protected global::System.Web.UI.WebControls.TextBox txtHtInMax;
        

        protected global::System.Web.UI.WebControls.CheckBox chkReduced;

        protected global::System.Web.UI.WebControls.DropDownList cboCondition;

        protected global::System.Web.UI.WebControls.DropDownList cboFins;
        

        protected global::System.Web.UI.WebControls.DropDownList cboTailType;

        protected global::System.Web.UI.WebControls.DropDownList cboAdType;

        protected global::System.Web.UI.WebControls.DropDownList cboPostingType;
        
        protected global::System.Web.UI.WebControls.Button btnSearch;

        protected global::System.Web.UI.WebControls.LinkButton toplnkFirst;

        protected global::System.Web.UI.WebControls.ImageButton topcmdPrev;
        

        protected global::System.Web.UI.WebControls.Label toplblcpage;

        protected global::System.Web.UI.WebControls.ImageButton topcmdNext;

		//protected global::System.Web.UI.WebControls.DataList dlEntryList;

        protected global::System.Web.UI.WebControls.ImageButton cmdPrev;

        protected global::System.Web.UI.WebControls.Label lblcpage;
	
        protected global::System.Web.UI.WebControls.ImageButton cmdNext;

        protected global::System.Web.UI.WebControls.LinkButton lnkFirst;  
        protected global::System.Web.UI.WebControls.LinkButton lnkLast;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnBackColor;
	
        protected global::System.Web.UI.WebControls.HiddenField hdnLocVal;
        protected global::System.Web.UI.WebControls.HiddenField hdniCat;
        protected global::System.Web.UI.WebControls.HiddenField hdnServer;
        protected global::System.Web.UI.WebControls.HiddenField hdniBoardType;
        protected global::System.Web.UI.WebControls.HiddenField hdnKeywords;
        protected global::System.Web.UI.WebControls.HiddenField hdnUiD;
        protected global::System.Web.UI.WebControls.HiddenField hdnSash;
        protected global::System.Web.UI.WebControls.Button btnUpdates;
        protected global::System.Web.UI.WebControls.Label lblMessage;
	}
}
