// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BoardHunt {
	
	
	public partial class UserMenu {
		
		protected System.Web.UI.HtmlControls.HtmlForm Form1;
		
		protected System.Web.UI.WebControls.Label lblMessage;
		
		protected System.Web.UI.WebControls.HyperLink hypAcctEdit;
		
		protected System.Web.UI.WebControls.ImageButton imgBtnAcct;
		
		protected System.Web.UI.WebControls.Button btnUpgradePro;
		
		protected System.Web.UI.WebControls.LinkButton lnkEditProfile;
		
		protected System.Web.UI.WebControls.LinkButton lnkFav;
		
		protected System.Web.UI.WebControls.Panel pnlShaper;
		
		protected System.Web.UI.WebControls.ImageButton imgBtnShapers;
		
		protected System.Web.UI.WebControls.Panel pnlShaperBuy;
		
		protected System.Web.UI.WebControls.ImageButton btnBuyShaper;
		
		protected System.Web.UI.WebControls.LinkButton lnkShaperMoreInfo;
		
		protected System.Web.UI.WebControls.Panel pnlShaperCtls;
		
		protected System.Web.UI.WebControls.LinkButton lnkAddNewModel;
		
		protected System.Web.UI.WebControls.LinkButton lnkEditModel;
		
		protected System.Web.UI.WebControls.Panel pnlQP;
		
		protected System.Web.UI.WebControls.ImageButton imgBtnQPon;
		
		protected System.Web.UI.WebControls.LinkButton lnkBuyQP;
		
		protected System.Web.UI.WebControls.LinkButton lnkManageQP;
		
		protected System.Web.UI.WebControls.LinkButton lnkSettings;
		
		protected System.Web.UI.WebControls.ImageButton ImageButton1;
		
		protected System.Web.UI.WebControls.Label lblBoardCount;
		
		protected System.Web.UI.WebControls.LinkButton lnkSellGear;
		
		protected System.Web.UI.WebControls.LinkButton lnkEditGear;
		
		protected System.Web.UI.WebControls.ImageButton ImageButton2;
		
		protected System.Web.UI.WebControls.LinkButton lnkAskNew;
		
		protected System.Web.UI.WebControls.LinkButton lnkAskEdit;
		
		protected System.Web.UI.WebControls.Panel pnlShowcase;
		
		protected System.Web.UI.WebControls.ImageButton ImageButton4;
		
		protected System.Web.UI.WebControls.LinkButton lnkShowcaseNew;
		
		protected System.Web.UI.WebControls.Panel pnlBlog;
		
		protected System.Web.UI.WebControls.ImageButton ImageButton5;
		
		protected System.Web.UI.WebControls.LinkButton lnkBlogNew;
		
		protected System.Web.UI.WebControls.LinkButton lnkBlogEdit;
		
		protected System.Web.UI.WebControls.Panel pnlBidder;
		
		protected System.Web.UI.WebControls.ImageButton imgBidder;
		
		protected System.Web.UI.WebControls.Panel pnlSUB;
		
		protected System.Web.UI.WebControls.ImageButton imgBtnSubscription;
		
		protected System.Web.UI.WebControls.HiddenField hdnACT;
		
		protected System.Web.UI.WebControls.HiddenField hdnMT;
		
		protected System.Web.UI.WebControls.HiddenField hdnShaperAcctValid;
	}
}
