// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BoardHunt.Shaper {
	
	
	public partial class SurfboardShaper {
		
		protected System.Web.UI.WebControls.ImageButton imgBtnModel;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton3;
		
		protected System.Web.UI.WebControls.LinkButton lnkViewNow;
	}
}
